FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 8050

# Set environment variable for the API URL
ENV API_BASE_URL=http://api:8001/api

CMD ["python", "src/dashboard/app.py"]
